# INSTALL GENERAL DEPENDANCIES
- name : "Install dependancies"
  become: yes
  become_user: root
  apt:
    pkg: ['postgresql-13-postgis-3', 'postgis', 'postgresql-contrib', 'supervisor', 'curl', 'git']
    update_cache: yes
    state: present
  when: ansible_distribution_release == "bullseye"

# INSTALL PYTHON DEPENDANCIES
- name : "Install python3 dependencies"
  become: yes
  become_user: root
  apt: 
    pkg: ['python3', 'python3-dev', 'python3-setuptools', 'python3-pip', 'python3-virtualenv', 'python3-venv', 'libpq-dev', 'python3-psycopg2']
    state: present
    update_cache: yes
  when: ansible_distribution_release == "bullseye"

# INSTALL APACHE
- name: install apache2
  become: yes
  become_user: root
  apt:
    pkg: apache2
    state: present

# INSTALL VENV
- name: install virtualenv from pip
  become: yes
  become_user: root
  pip:
    name: virtualenv==20.0.1

# USE OTHERS YML IN THE SAME FOLDER
- include: "{{item}}.yml"
  with_items:
  - node
  - git