- name: Copy settings file
  template:
    src: settings.j2
    dest: /home/synthese/usershub/config/settings.ini
- name: Copy config file
  template:
    src: config.j2
    dest: /home/synthese/usershub/config/config.ini