## CREATE CONFIG FILES
- name: Copy config file
  template:
    src: "config.j2"
    dest: "~/usershub/config/config.py"

- name: Copy settings file
  template:
    src: "settings.j2"
    dest: "~/usershub/config/settings.ini"

- include: "{{item}}.yml"
  with_items:
  - venv
  - nodejs
  - daemon
  - apache